# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\kccistc\Desktop\smart-monitoring-system\qt-server\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 900)
        MainWindow.setMinimumSize(QtCore.QSize(680, 800))
        MainWindow.setStyleSheet("/* 메인 배경 및 기본 폰트 설정 */\n"
"QMainWindow {\n"
"    background-color: #F5F5F7;\n"
"    font-family: \"Malgun Gothic\", \"Segoe UI\", sans-serif;\n"
"}\n"
"\n"
"/* 그룹박스 헤더 및 테두리 스타일링 */\n"
"QGroupBox {\n"
"    font-weight: bold;\n"
"    font-size: 10pt;\n"
"    color: #1D1D1F;\n"
"    border: 1px solid #D2D2D7;\n"
"    border-radius: 8px;\n"
"    margin-top: 10px;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 8px;\n"
"    left: 10px;\n"
"}\n"
"\n"
"/* 입력 필드 공통 스타일 */\n"
"QLineEdit, QComboBox, QSpinBox {\n"
"    border: 1px solid #C7C7CC;\n"
"    border-radius: 4px;\n"
"    padding: 2px 5px;\n"
"    background-color: #FAFAFC;\n"
"    color: #1D1D1F;\n"
"}\n"
"\n"
"QLineEdit:focus, QComboBox:focus, QSpinBox:focus {\n"
"    border: 1px solid #007AFF;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"/* 버튼 일반 기본 스타일 */\n"
"QPushButton {\n"
"    background-color: #E5E5EA;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: #1D1D1F;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D1D1D6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #C7C7CC;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gbCctv = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbCctv.sizePolicy().hasHeightForWidth())
        self.gbCctv.setSizePolicy(sizePolicy)
        self.gbCctv.setObjectName("gbCctv")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbCctv)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblCameraPreview = QtWidgets.QLabel(self.gbCctv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCameraPreview.sizePolicy().hasHeightForWidth())
        self.lblCameraPreview.setSizePolicy(sizePolicy)
        self.lblCameraPreview.setMinimumSize(QtCore.QSize(0, 0))
        self.lblCameraPreview.setStyleSheet("background-color: #000000;\n"
"border-radius: 6px;")
        self.lblCameraPreview.setText("")
        self.lblCameraPreview.setScaledContents(False)
        self.lblCameraPreview.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignCenter)
        self.lblCameraPreview.setObjectName("lblCameraPreview")
        self.verticalLayout_2.addWidget(self.lblCameraPreview)
        self.horizontalLayout_5.addWidget(self.gbCctv)
        self.gbControl = QtWidgets.QGroupBox(self.centralwidget)
        self.gbControl.setMaximumSize(QtCore.QSize(380, 16777215))
        self.gbControl.setObjectName("gbControl")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbControl)
        self.verticalLayout_3.setContentsMargins(10, 12, 10, 10)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblTcpServer = QtWidgets.QLabel(self.gbControl)
        self.lblTcpServer.setStyleSheet("color: #0055FF; font-weight: bold;")
        self.lblTcpServer.setObjectName("lblTcpServer")
        self.horizontalLayout_2.addWidget(self.lblTcpServer)
        self.lblServerIp = QtWidgets.QLabel(self.gbControl)
        self.lblServerIp.setStyleSheet("color: #666666; font-size: 8.5pt;")
        self.lblServerIp.setObjectName("lblServerIp")
        self.horizontalLayout_2.addWidget(self.lblServerIp)
        self.lePort = QtWidgets.QLineEdit(self.gbControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lePort.sizePolicy().hasHeightForWidth())
        self.lePort.setSizePolicy(sizePolicy)
        self.lePort.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lePort.setStyleSheet("max-width: 60px; height: 26px; AlignCenter")
        self.lePort.setObjectName("lePort")
        self.horizontalLayout_2.addWidget(self.lePort)
        self.btnStartServer = QtWidgets.QPushButton(self.gbControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStartServer.sizePolicy().hasHeightForWidth())
        self.btnStartServer.setSizePolicy(sizePolicy)
        self.btnStartServer.setMinimumSize(QtCore.QSize(90, 26))
        self.btnStartServer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnStartServer.setObjectName("btnStartServer")
        self.horizontalLayout_2.addWidget(self.btnStartServer)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.gbControl)
        self.label_2.setStyleSheet("color: #555555; font-size: 8.5pt;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.lblClientCount = QtWidgets.QLabel(self.gbControl)
        self.lblClientCount.setStyleSheet("color: #555555; font-size: 8.5pt;")
        self.lblClientCount.setObjectName("lblClientCount")
        self.horizontalLayout_8.addWidget(self.lblClientCount)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.line = QtWidgets.QFrame(self.gbControl)
        self.line.setStyleSheet("color: #E0E0E0;")
